name: PhoenixTools
version: '${project.version}'
main: net.resolutemc.phoenixtools.PhoenixTools
api-version: 1.19
authors: [ Mike3132 ]
description: ResoluteMC custom tools plugin
website: www.resolutemc.net
commands:
  tools:
    description: Main plugin command
